postgres:
  user: nkiver
  pwd: nkiver
  db: postgres
  image:
    pullPolicy: IfNotPresent
    repository: postgres
    tag: "14.8"
  ports:
    addressPort: 5432
    addressPortAlias: psql

newman:
  image:
    pullPolicy: Never
    repository: hbf_api_tests
    tag: "latest"
  reporter:
    user: nkiver
    password: nkiver
    host: test-db
    port: 5432
    name: postgres
    schema: hbf_api_results

HBFServer:
  image:
    pullPolicy: IfNotPresent
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/sgroups
    tag: "feature-postgres-30bd21ff"
  ports:
    addressPort: 9006
    addressPortAlias: hbf-server
  securityContext:
    privileged: true
  svc:
    pgPort: 5432
    serverPort: 80

gitlab:
  pipelineID: 312355
  src_branch: from
  dst_branch: to

defaults:
  securityContext: {}