apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-hbf-server
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ .Release.Name }}-hbf-server
spec:
  containers:
    {{- with .Values.HBFServer }}
    - name: hbf-server
      image: {{ .image.repository }}:{{ .image.tag }}
      imagePullPolicy: {{ .image.pullPolicy }}
      {{- with .securityContext | default $.Values.defaults.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumeMounts:
        - name: {{ $.Release.Name }}-hbf-server
          mountPath: /app/hack/configs/server.yaml
          subPath: conf.yaml 
      command: ["./bin/sgroups", "-config", "/app/hack/configs/server.yaml"]
      # command: ["./sgroups", "-config", "/app/hack/configs/server.yaml"]
      ports:
        - containerPort: {{ .ports.addressPort }}
          name: {{ .ports.addressPortAlias }}
      env:
        - name: SG_STORAGE_POSTGRES_URL
          value: postgres://{{ $.Values.postgres.user }}:{{ $.Values.postgres.pwd }}@localhost:5432/{{ $.Values.postgres.db }}?sslmode=disable
        - name: SG_STORAGE_TYPE
          value: postgres 
    {{- end }}

    {{- with .Values.postgres }}
    - name: pgsql
      image: {{ .image.repository }}:{{ .image.tag }}
      imagePullPolicy: {{ .image.pullPolicy }}
      {{- with .securityContext | default $.Values.defaults.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumeMounts:
        - name: {{ $.Release.Name }}-pg-init
          mountPath: /docker-entrypoint-initdb.d
      ports:
        - containerPort: {{ .ports.addressPort }}
          name: {{ .ports.addressPortAlias }}
      env:
        - name: POSTGRES_USER
          value: {{ .user }}
        - name: POSTGRES_PASSWORD
          value: {{ .pwd }}
        - name: POSTGRES_DB
          value: {{ .db }}
    {{- end}}

  volumes:
    - name: {{ .Release.Name }}-hbf-server
      configMap:
        name: {{ .Release.Name }}-hbf-server
    - name: {{ .Release.Name }}-pg-init
      configMap:
        name: {{ .Release.Name }}-pg-init