apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wait-db
  namespace: {{ .Release.Namespace }}
data:
  wait-db.sh: |
    #!/bin/sh

    until [ "$(psql postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$HBF_HOST:{{ .Values.postgres.ports.addressPort }}/postgres?sslmode=disable -c "SELECT COUNT(*) FROM sgroups.tbl_sg_rule;" -t -A)" -gt 0 ]; do
      echo "Ожидание непустой таблицы 'sgroups.tbl_sg_rule' в базе данных в Pod hbf-server..."
      sleep 5
    done

    echo "Таблица 'sgroups.tbl_sg_rule' в базе данных в Pod hbf-server не пустая. Продолжение работы основного контейнера..."
